2025-06-11 12:19:27|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-06-11 12:19:29|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-06-11 12:19:29|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-06-11 12:22:57|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-06-11 12:22:59|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-06-11 12:22:59|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-06-11 12:24:50|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-06-11 12:24:52|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-06-11 12:24:52|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-06-11 13:15:58|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-06-11 13:15:58|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-06-11 13:16:36|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-06-11 13:16:36|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-06-11 13:42:08|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-06-11 13:42:42|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-06-11 13:42:44|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-06-11 13:42:44|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-06-11 13:42:44|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-06-11 13:42:44|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-06-11 13:42:44|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-06-11 13:42:44|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-06-11 13:55:24|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-06-11 13:55:24|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-06-11 13:55:56|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-06-11 13:55:58|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-06-11 13:55:58|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-06-11 13:55:58|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-06-11 13:55:58|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-06-11 13:55:58|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-06-11 13:55:58|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-06-11 14:04:48|ERROR   |root                            |BAZARR SignalR client for Sonarr connection as been lost. Trying to reconnect...|
2025-06-11 14:04:48|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
2025-06-11 14:07:32|INFO    |root                            |Scheduler will use this timezone: Etc/UTC|
2025-06-11 14:07:34|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
2025-06-11 14:07:34|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://***.***.***.***:6767|
2025-06-11 14:07:34|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
2025-06-11 14:07:34|INFO    |waitress                        |BAZARR is started and waiting for requests on: http://[::]:6767|
2025-06-11 14:07:34|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
2025-06-11 14:07:34|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
2025-06-11 15:53:21|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/195?apikey=(removed)'|
2025-06-11 15:53:21|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/196?apikey=(removed)'|
2025-06-11 15:53:21|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/197?apikey=(removed)'|
2025-06-11 15:53:21|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/198?apikey=(removed)'|
2025-06-11 15:53:21|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/199?apikey=(removed)'|
2025-06-11 15:53:21|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/200?apikey=(removed)'|
2025-06-11 15:53:21|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/201?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/202?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/203?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/204?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/205?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/206?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/207?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/208?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/209?apikey=(removed)'|
2025-06-11 15:53:22|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/210?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/212?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/213?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/214?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/215?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/216?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/217?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/218?apikey=(removed)'|
2025-06-11 15:53:23|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/195?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/196?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/197?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/198?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/199?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/200?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/201?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/202?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/203?apikey=(removed)'|
2025-06-11 15:53:24|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/204?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/205?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/206?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/207?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/208?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/209?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/210?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/212?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/213?apikey=(removed)'|
2025-06-11 15:53:25|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/214?apikey=(removed)'|
2025-06-11 15:53:26|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/215?apikey=(removed)'|
2025-06-11 15:53:26|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/216?apikey=(removed)'|
2025-06-11 15:53:26|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/217?apikey=(removed)'|
2025-06-11 15:53:26|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/218?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/195?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/196?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/197?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/198?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/199?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/200?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/201?apikey=(removed)'|
2025-06-11 15:55:08|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/202?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/203?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/204?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/205?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/206?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/207?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/208?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/209?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/210?apikey=(removed)'|
2025-06-11 15:55:09|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/212?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/213?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/214?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/215?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/216?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/217?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/218?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/195?apikey=(removed)'|
2025-06-11 15:55:10|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/196?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/197?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/198?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/199?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/200?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/201?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/202?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/203?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/204?apikey=(removed)'|
2025-06-11 15:55:11|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/205?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/206?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/207?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/208?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/209?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/210?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/212?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/213?apikey=(removed)'|
2025-06-11 15:55:12|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/214?apikey=(removed)'|
2025-06-11 15:55:13|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/215?apikey=(removed)'|
2025-06-11 15:55:13|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/216?apikey=(removed)'|
2025-06-11 15:55:13|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/217?apikey=(removed)'|
2025-06-11 15:55:13|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/sync/utils.py", line 116, in get_episodes_from_sonarr_api\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://***.***.***.***:8989/api/v3/episode/218?apikey=(removed)'|
